version: '3'
services:
  backend:
    build: .
    working_dir: /app
    command: pipenv run uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload
    environment:
      DEBUG: 1
    volumes:
      - .:/app
    ports:
      - 3000:3000
    restart: always
